version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - "/data/mongodb/data:/data/db"
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    volumes:
      - "/data/redis/data/:/data"
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: nblog
    volumes:
      - "/data/logs/nblog/logs/:/app/logs"
    ports:
      - "8015:80"
    depends_on:
      - mongodb
      - redis
